// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/protocol/protocol.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloMessage struct {
	UdpPort              uint32   `protobuf:"varint,1,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloMessage) Reset()         { *m = HelloMessage{} }
func (m *HelloMessage) String() string { return proto.CompactTextString(m) }
func (*HelloMessage) ProtoMessage()    {}
func (*HelloMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{0}
}

func (m *HelloMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloMessage.Unmarshal(m, b)
}
func (m *HelloMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloMessage.Marshal(b, m, deterministic)
}
func (m *HelloMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloMessage.Merge(m, src)
}
func (m *HelloMessage) XXX_Size() int {
	return xxx_messageInfo_HelloMessage.Size(m)
}
func (m *HelloMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HelloMessage proto.InternalMessageInfo

func (m *HelloMessage) GetUdpPort() uint32 {
	if m != nil {
		return m.UdpPort
	}
	return 0
}

type SetStationMessage struct {
	StationNumber        uint32   `protobuf:"varint,1,opt,name=station_number,json=stationNumber,proto3" json:"station_number,omitempty"`
	UdpPort              uint32   `protobuf:"varint,2,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStationMessage) Reset()         { *m = SetStationMessage{} }
func (m *SetStationMessage) String() string { return proto.CompactTextString(m) }
func (*SetStationMessage) ProtoMessage()    {}
func (*SetStationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{1}
}

func (m *SetStationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStationMessage.Unmarshal(m, b)
}
func (m *SetStationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStationMessage.Marshal(b, m, deterministic)
}
func (m *SetStationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStationMessage.Merge(m, src)
}
func (m *SetStationMessage) XXX_Size() int {
	return xxx_messageInfo_SetStationMessage.Size(m)
}
func (m *SetStationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SetStationMessage proto.InternalMessageInfo

func (m *SetStationMessage) GetStationNumber() uint32 {
	if m != nil {
		return m.StationNumber
	}
	return 0
}

func (m *SetStationMessage) GetUdpPort() uint32 {
	if m != nil {
		return m.UdpPort
	}
	return 0
}

type WelcomeMessage struct {
	NumStations          uint32   `protobuf:"varint,1,opt,name=num_stations,json=numStations,proto3" json:"num_stations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WelcomeMessage) Reset()         { *m = WelcomeMessage{} }
func (m *WelcomeMessage) String() string { return proto.CompactTextString(m) }
func (*WelcomeMessage) ProtoMessage()    {}
func (*WelcomeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{2}
}

func (m *WelcomeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WelcomeMessage.Unmarshal(m, b)
}
func (m *WelcomeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WelcomeMessage.Marshal(b, m, deterministic)
}
func (m *WelcomeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WelcomeMessage.Merge(m, src)
}
func (m *WelcomeMessage) XXX_Size() int {
	return xxx_messageInfo_WelcomeMessage.Size(m)
}
func (m *WelcomeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WelcomeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WelcomeMessage proto.InternalMessageInfo

func (m *WelcomeMessage) GetNumStations() uint32 {
	if m != nil {
		return m.NumStations
	}
	return 0
}

type AnnounceMessage struct {
	SongName             string   `protobuf:"bytes,1,opt,name=song_name,json=songName,proto3" json:"song_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnounceMessage) Reset()         { *m = AnnounceMessage{} }
func (m *AnnounceMessage) String() string { return proto.CompactTextString(m) }
func (*AnnounceMessage) ProtoMessage()    {}
func (*AnnounceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{3}
}

func (m *AnnounceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnounceMessage.Unmarshal(m, b)
}
func (m *AnnounceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnounceMessage.Marshal(b, m, deterministic)
}
func (m *AnnounceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnounceMessage.Merge(m, src)
}
func (m *AnnounceMessage) XXX_Size() int {
	return xxx_messageInfo_AnnounceMessage.Size(m)
}
func (m *AnnounceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnounceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AnnounceMessage proto.InternalMessageInfo

func (m *AnnounceMessage) GetSongName() string {
	if m != nil {
		return m.SongName
	}
	return ""
}

type InvalidCommandMessage struct {
	ReplyString          string   `protobuf:"bytes,1,opt,name=reply_string,json=replyString,proto3" json:"reply_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidCommandMessage) Reset()         { *m = InvalidCommandMessage{} }
func (m *InvalidCommandMessage) String() string { return proto.CompactTextString(m) }
func (*InvalidCommandMessage) ProtoMessage()    {}
func (*InvalidCommandMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{4}
}

func (m *InvalidCommandMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidCommandMessage.Unmarshal(m, b)
}
func (m *InvalidCommandMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidCommandMessage.Marshal(b, m, deterministic)
}
func (m *InvalidCommandMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidCommandMessage.Merge(m, src)
}
func (m *InvalidCommandMessage) XXX_Size() int {
	return xxx_messageInfo_InvalidCommandMessage.Size(m)
}
func (m *InvalidCommandMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidCommandMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidCommandMessage proto.InternalMessageInfo

func (m *InvalidCommandMessage) GetReplyString() string {
	if m != nil {
		return m.ReplyString
	}
	return ""
}

type DisconnectRequest struct {
	UdpPort              uint32   `protobuf:"varint,2,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{5}
}

func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(m, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

func (m *DisconnectRequest) GetUdpPort() uint32 {
	if m != nil {
		return m.UdpPort
	}
	return 0
}

type DisconnectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectResponse) Reset()         { *m = DisconnectResponse{} }
func (m *DisconnectResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectResponse) ProtoMessage()    {}
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{6}
}

func (m *DisconnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResponse.Unmarshal(m, b)
}
func (m *DisconnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResponse.Marshal(b, m, deterministic)
}
func (m *DisconnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResponse.Merge(m, src)
}
func (m *DisconnectResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectResponse.Size(m)
}
func (m *DisconnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResponse proto.InternalMessageInfo

func (m *DisconnectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ServerEvent struct {
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Announce
	//	*ServerEvent_Invalid
	Event                isServerEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ServerEvent) Reset()         { *m = ServerEvent{} }
func (m *ServerEvent) String() string { return proto.CompactTextString(m) }
func (*ServerEvent) ProtoMessage()    {}
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{7}
}

func (m *ServerEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerEvent.Unmarshal(m, b)
}
func (m *ServerEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerEvent.Marshal(b, m, deterministic)
}
func (m *ServerEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerEvent.Merge(m, src)
}
func (m *ServerEvent) XXX_Size() int {
	return xxx_messageInfo_ServerEvent.Size(m)
}
func (m *ServerEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ServerEvent proto.InternalMessageInfo

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Announce struct {
	Announce *AnnounceMessage `protobuf:"bytes,1,opt,name=announce,proto3,oneof"`
}

type ServerEvent_Invalid struct {
	Invalid *InvalidCommandMessage `protobuf:"bytes,2,opt,name=invalid,proto3,oneof"`
}

func (*ServerEvent_Announce) isServerEvent_Event() {}

func (*ServerEvent_Invalid) isServerEvent_Event() {}

func (m *ServerEvent) GetEvent() isServerEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ServerEvent) GetAnnounce() *AnnounceMessage {
	if x, ok := m.GetEvent().(*ServerEvent_Announce); ok {
		return x.Announce
	}
	return nil
}

func (m *ServerEvent) GetInvalid() *InvalidCommandMessage {
	if x, ok := m.GetEvent().(*ServerEvent_Invalid); ok {
		return x.Invalid
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerEvent_Announce)(nil),
		(*ServerEvent_Invalid)(nil),
	}
}

type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{8}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type HealthResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{9}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type HandshakeOp struct {
	ClientIp             string   `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UdpPort              uint32   `protobuf:"varint,2,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeOp) Reset()         { *m = HandshakeOp{} }
func (m *HandshakeOp) String() string { return proto.CompactTextString(m) }
func (*HandshakeOp) ProtoMessage()    {}
func (*HandshakeOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{10}
}

func (m *HandshakeOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeOp.Unmarshal(m, b)
}
func (m *HandshakeOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeOp.Marshal(b, m, deterministic)
}
func (m *HandshakeOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeOp.Merge(m, src)
}
func (m *HandshakeOp) XXX_Size() int {
	return xxx_messageInfo_HandshakeOp.Size(m)
}
func (m *HandshakeOp) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeOp.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeOp proto.InternalMessageInfo

func (m *HandshakeOp) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *HandshakeOp) GetUdpPort() uint32 {
	if m != nil {
		return m.UdpPort
	}
	return 0
}

type SetStationOp struct {
	ClientIp             string   `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UdpPort              uint32   `protobuf:"varint,2,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	StationNumber        int32    `protobuf:"varint,3,opt,name=station_number,json=stationNumber,proto3" json:"station_number,omitempty"`
	PreviousStation      int32    `protobuf:"varint,4,opt,name=previous_station,json=previousStation,proto3" json:"previous_station,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStationOp) Reset()         { *m = SetStationOp{} }
func (m *SetStationOp) String() string { return proto.CompactTextString(m) }
func (*SetStationOp) ProtoMessage()    {}
func (*SetStationOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{11}
}

func (m *SetStationOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStationOp.Unmarshal(m, b)
}
func (m *SetStationOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStationOp.Marshal(b, m, deterministic)
}
func (m *SetStationOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStationOp.Merge(m, src)
}
func (m *SetStationOp) XXX_Size() int {
	return xxx_messageInfo_SetStationOp.Size(m)
}
func (m *SetStationOp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStationOp.DiscardUnknown(m)
}

var xxx_messageInfo_SetStationOp proto.InternalMessageInfo

func (m *SetStationOp) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *SetStationOp) GetUdpPort() uint32 {
	if m != nil {
		return m.UdpPort
	}
	return 0
}

func (m *SetStationOp) GetStationNumber() int32 {
	if m != nil {
		return m.StationNumber
	}
	return 0
}

func (m *SetStationOp) GetPreviousStation() int32 {
	if m != nil {
		return m.PreviousStation
	}
	return 0
}

type DisconnectOp struct {
	ClientIp             string   `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UdpPort              uint32   `protobuf:"varint,2,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectOp) Reset()         { *m = DisconnectOp{} }
func (m *DisconnectOp) String() string { return proto.CompactTextString(m) }
func (*DisconnectOp) ProtoMessage()    {}
func (*DisconnectOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{12}
}

func (m *DisconnectOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectOp.Unmarshal(m, b)
}
func (m *DisconnectOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectOp.Marshal(b, m, deterministic)
}
func (m *DisconnectOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectOp.Merge(m, src)
}
func (m *DisconnectOp) XXX_Size() int {
	return xxx_messageInfo_DisconnectOp.Size(m)
}
func (m *DisconnectOp) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectOp.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectOp proto.InternalMessageInfo

func (m *DisconnectOp) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *DisconnectOp) GetUdpPort() uint32 {
	if m != nil {
		return m.UdpPort
	}
	return 0
}

type WalEntry struct {
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*WalEntry_Handshake
	//	*WalEntry_SetStation
	//	*WalEntry_Disconnect
	Op                   isWalEntry_Op `protobuf_oneof:"op"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WalEntry) Reset()         { *m = WalEntry{} }
func (m *WalEntry) String() string { return proto.CompactTextString(m) }
func (*WalEntry) ProtoMessage()    {}
func (*WalEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{13}
}

func (m *WalEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalEntry.Unmarshal(m, b)
}
func (m *WalEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalEntry.Marshal(b, m, deterministic)
}
func (m *WalEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalEntry.Merge(m, src)
}
func (m *WalEntry) XXX_Size() int {
	return xxx_messageInfo_WalEntry.Size(m)
}
func (m *WalEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_WalEntry.DiscardUnknown(m)
}

var xxx_messageInfo_WalEntry proto.InternalMessageInfo

func (m *WalEntry) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type isWalEntry_Op interface {
	isWalEntry_Op()
}

type WalEntry_Handshake struct {
	Handshake *HandshakeOp `protobuf:"bytes,2,opt,name=handshake,proto3,oneof"`
}

type WalEntry_SetStation struct {
	SetStation *SetStationOp `protobuf:"bytes,3,opt,name=set_station,json=setStation,proto3,oneof"`
}

type WalEntry_Disconnect struct {
	Disconnect *DisconnectOp `protobuf:"bytes,4,opt,name=disconnect,proto3,oneof"`
}

func (*WalEntry_Handshake) isWalEntry_Op() {}

func (*WalEntry_SetStation) isWalEntry_Op() {}

func (*WalEntry_Disconnect) isWalEntry_Op() {}

func (m *WalEntry) GetOp() isWalEntry_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *WalEntry) GetHandshake() *HandshakeOp {
	if x, ok := m.GetOp().(*WalEntry_Handshake); ok {
		return x.Handshake
	}
	return nil
}

func (m *WalEntry) GetSetStation() *SetStationOp {
	if x, ok := m.GetOp().(*WalEntry_SetStation); ok {
		return x.SetStation
	}
	return nil
}

func (m *WalEntry) GetDisconnect() *DisconnectOp {
	if x, ok := m.GetOp().(*WalEntry_Disconnect); ok {
		return x.Disconnect
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WalEntry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WalEntry_Handshake)(nil),
		(*WalEntry_SetStation)(nil),
		(*WalEntry_Disconnect)(nil),
	}
}

type ReplicateRequest struct {
	Entry                *WalEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReplicateRequest) Reset()         { *m = ReplicateRequest{} }
func (m *ReplicateRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicateRequest) ProtoMessage()    {}
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{14}
}

func (m *ReplicateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateRequest.Unmarshal(m, b)
}
func (m *ReplicateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateRequest.Marshal(b, m, deterministic)
}
func (m *ReplicateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateRequest.Merge(m, src)
}
func (m *ReplicateRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicateRequest.Size(m)
}
func (m *ReplicateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateRequest proto.InternalMessageInfo

func (m *ReplicateRequest) GetEntry() *WalEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type ReplicateResponse struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicateResponse) Reset()         { *m = ReplicateResponse{} }
func (m *ReplicateResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicateResponse) ProtoMessage()    {}
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{15}
}

func (m *ReplicateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateResponse.Unmarshal(m, b)
}
func (m *ReplicateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateResponse.Marshal(b, m, deterministic)
}
func (m *ReplicateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateResponse.Merge(m, src)
}
func (m *ReplicateResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicateResponse.Size(m)
}
func (m *ReplicateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateResponse proto.InternalMessageInfo

func (m *ReplicateResponse) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *ReplicateResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *ReplicateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{16}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	LastWalSeq           uint64   `protobuf:"varint,1,opt,name=last_wal_seq,json=lastWalSeq,proto3" json:"last_wal_seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc91bbc4f8ea82bc, []int{17}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetLastWalSeq() uint64 {
	if m != nil {
		return m.LastWalSeq
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloMessage)(nil), "protocol.HelloMessage")
	proto.RegisterType((*SetStationMessage)(nil), "protocol.SetStationMessage")
	proto.RegisterType((*WelcomeMessage)(nil), "protocol.WelcomeMessage")
	proto.RegisterType((*AnnounceMessage)(nil), "protocol.AnnounceMessage")
	proto.RegisterType((*InvalidCommandMessage)(nil), "protocol.InvalidCommandMessage")
	proto.RegisterType((*DisconnectRequest)(nil), "protocol.DisconnectRequest")
	proto.RegisterType((*DisconnectResponse)(nil), "protocol.DisconnectResponse")
	proto.RegisterType((*ServerEvent)(nil), "protocol.ServerEvent")
	proto.RegisterType((*HealthRequest)(nil), "protocol.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "protocol.HealthResponse")
	proto.RegisterType((*HandshakeOp)(nil), "protocol.HandshakeOp")
	proto.RegisterType((*SetStationOp)(nil), "protocol.SetStationOp")
	proto.RegisterType((*DisconnectOp)(nil), "protocol.DisconnectOp")
	proto.RegisterType((*WalEntry)(nil), "protocol.WalEntry")
	proto.RegisterType((*ReplicateRequest)(nil), "protocol.ReplicateRequest")
	proto.RegisterType((*ReplicateResponse)(nil), "protocol.ReplicateResponse")
	proto.RegisterType((*PingRequest)(nil), "protocol.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "protocol.PingResponse")
}

func init() {
	proto.RegisterFile("pkg/protocol/protocol.proto", fileDescriptor_cc91bbc4f8ea82bc)
}

var fileDescriptor_cc91bbc4f8ea82bc = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdf, 0x4f, 0xeb, 0x36,
	0x14, 0x6e, 0x4a, 0x4b, 0xdb, 0x93, 0xfe, 0x00, 0x6f, 0xb0, 0xd2, 0x4e, 0x5a, 0x17, 0x6d, 0x12,
	0x3c, 0xac, 0xa0, 0x22, 0x34, 0x36, 0xb6, 0x87, 0x15, 0xd8, 0x8a, 0xa6, 0x31, 0x94, 0x6a, 0x42,
	0xda, 0x4b, 0x64, 0x52, 0xab, 0x64, 0x4d, 0xec, 0x10, 0x3b, 0x45, 0xfc, 0x0f, 0x7b, 0xda, 0xd3,
	0x74, 0xff, 0xa8, 0xfb, 0x37, 0x5d, 0x25, 0xb1, 0x13, 0xb7, 0x54, 0x3c, 0xdc, 0xfb, 0xe6, 0x73,
	0x72, 0xbe, 0x63, 0x7f, 0xdf, 0x77, 0xec, 0x40, 0x3f, 0x5c, 0xcc, 0x8f, 0xc3, 0x88, 0x09, 0xe6,
	0x32, 0x3f, 0x5f, 0x0c, 0xd3, 0x05, 0xaa, 0xab, 0xd8, 0x3a, 0x82, 0xe6, 0x84, 0xf8, 0x3e, 0xfb,
	0x83, 0x70, 0x8e, 0xe7, 0x04, 0x1d, 0x40, 0x3d, 0x9e, 0x85, 0x4e, 0xc8, 0x22, 0xd1, 0x35, 0x06,
	0xc6, 0x61, 0xcb, 0xae, 0xc5, 0xb3, 0xf0, 0x8e, 0x45, 0xc2, 0xfa, 0x0b, 0x76, 0xa7, 0x44, 0x4c,
	0x05, 0x16, 0x1e, 0xa3, 0xaa, 0xfe, 0x5b, 0x68, 0xf3, 0x2c, 0xe3, 0xd0, 0x38, 0x78, 0x20, 0x91,
	0x44, 0xb5, 0x64, 0xf6, 0x36, 0x4d, 0xae, 0xb4, 0x2d, 0xaf, 0xb6, 0x3d, 0x85, 0xf6, 0x3d, 0xf1,
	0x5d, 0x16, 0x10, 0xd5, 0xf3, 0x6b, 0x68, 0xd2, 0x38, 0x70, 0x64, 0x07, 0x2e, 0x3b, 0x9a, 0x34,
	0x0e, 0xe4, 0xe6, 0xdc, 0x1a, 0x42, 0xe7, 0x17, 0x4a, 0x59, 0x4c, 0xdd, 0x1c, 0xd5, 0x87, 0x06,
	0x67, 0x74, 0xee, 0x50, 0x1c, 0x90, 0x14, 0xd2, 0xb0, 0xeb, 0x49, 0xe2, 0x16, 0x07, 0xc4, 0xfa,
	0x11, 0xf6, 0x6e, 0xe8, 0x12, 0xfb, 0xde, 0xec, 0x92, 0x05, 0x01, 0xa6, 0x33, 0x6d, 0xaf, 0x88,
	0x84, 0xfe, 0x8b, 0xc3, 0x45, 0xe4, 0xd1, 0xb9, 0x04, 0x9a, 0x69, 0x6e, 0x9a, 0xa6, 0xac, 0x21,
	0xec, 0x5e, 0x79, 0xdc, 0x65, 0x94, 0x12, 0x57, 0xd8, 0xe4, 0x29, 0x26, 0x5c, 0xbc, 0x45, 0x68,
	0x08, 0x48, 0xaf, 0xe7, 0x21, 0xa3, 0x9c, 0xa0, 0x2e, 0xd4, 0x78, 0xec, 0xba, 0x84, 0x67, 0x7c,
	0xea, 0xb6, 0x0a, 0xad, 0x7f, 0x0d, 0x30, 0xa7, 0x24, 0x5a, 0x92, 0xe8, 0x7a, 0x49, 0xa8, 0x40,
	0xdf, 0x43, 0x1d, 0x4b, 0x6e, 0x69, 0xa9, 0x39, 0x3a, 0x18, 0xe6, 0xfe, 0xad, 0xb1, 0x9e, 0x94,
	0xec, 0xbc, 0x18, 0x5d, 0x40, 0xcd, 0xcb, 0x48, 0xa6, 0x47, 0x32, 0x47, 0x5f, 0x15, 0xb8, 0x8d,
	0xec, 0x27, 0x25, 0x5b, 0x21, 0xc6, 0x35, 0xa8, 0x92, 0x64, 0x7b, 0xab, 0x03, 0xad, 0x09, 0xc1,
	0xbe, 0x78, 0x94, 0x54, 0xad, 0x01, 0xb4, 0x55, 0x42, 0x72, 0x69, 0x43, 0x99, 0x2d, 0x24, 0x8d,
	0x32, 0x5b, 0x58, 0xd7, 0x60, 0x4e, 0x30, 0x9d, 0xf1, 0x47, 0xbc, 0x20, 0x7f, 0x86, 0x89, 0x13,
	0xae, 0xef, 0x11, 0x2a, 0x1c, 0x2f, 0x54, 0x4e, 0x64, 0x89, 0x9b, 0xf0, 0x2d, 0xe1, 0xfe, 0x37,
	0xa0, 0x59, 0x4c, 0xd8, 0xc7, 0x37, 0xda, 0x30, 0x94, 0x5b, 0x03, 0xe3, 0xb0, 0xba, 0x3e, 0x94,
	0x47, 0xb0, 0x13, 0x46, 0x64, 0xe9, 0xb1, 0x98, 0xab, 0x61, 0xeb, 0x56, 0xd2, 0xc2, 0x8e, 0xca,
	0xcb, 0xb3, 0x58, 0xbf, 0x42, 0xb3, 0xf0, 0xf4, 0x13, 0x28, 0xbe, 0x37, 0xa0, 0x7e, 0x8f, 0xfd,
	0x6b, 0x2a, 0xa2, 0x17, 0xb4, 0x03, 0x5b, 0x9c, 0x3c, 0xa5, 0xf0, 0x8a, 0x9d, 0x2c, 0xd1, 0x19,
	0x34, 0x1e, 0x95, 0x90, 0xd2, 0xc3, 0xbd, 0xc2, 0x43, 0x4d, 0xe3, 0x49, 0xc9, 0x2e, 0x2a, 0xd1,
	0x0f, 0x60, 0x72, 0x22, 0x72, 0x0e, 0x5b, 0x29, 0x70, 0xbf, 0x00, 0xea, 0xa2, 0x4e, 0x4a, 0x36,
	0xf0, 0x3c, 0x46, 0xe7, 0x00, 0xb3, 0x9c, 0x58, 0xca, 0x7e, 0x05, 0xa9, 0x93, 0x4e, 0x90, 0x45,
	0xed, 0xb8, 0x02, 0x65, 0x16, 0x5a, 0x3f, 0xc1, 0x8e, 0x4d, 0x42, 0xdf, 0x73, 0xb1, 0x20, 0xea,
	0x6e, 0x1c, 0x42, 0x95, 0x24, 0x04, 0xe5, 0xf4, 0xa2, 0xa2, 0x9d, 0xa2, 0x6e, 0x67, 0x05, 0xd6,
	0xef, 0xb0, 0xab, 0xa1, 0xe5, 0x74, 0xbd, 0x96, 0x25, 0x9b, 0xb7, 0xb2, 0x9a, 0x37, 0xf4, 0x39,
	0x54, 0x49, 0x14, 0xb1, 0xcc, 0xd6, 0x86, 0x9d, 0x05, 0x56, 0x0b, 0xcc, 0x3b, 0x8f, 0xce, 0xd5,
	0xd8, 0x9e, 0x40, 0x33, 0x0b, 0x65, 0xdb, 0x01, 0x34, 0x7d, 0xcc, 0x85, 0xf3, 0x8c, 0x7d, 0xa7,
	0xe8, 0x0f, 0x49, 0xee, 0x1e, 0xfb, 0x53, 0xf2, 0x34, 0x7a, 0x57, 0x86, 0xce, 0x94, 0xb2, 0x67,
	0x17, 0x73, 0x71, 0xc9, 0xa8, 0x88, 0x98, 0x8f, 0x7e, 0x86, 0x46, 0x2e, 0x3b, 0xd2, 0x84, 0xd1,
	0x1f, 0xcd, 0x5e, 0x57, 0x63, 0xb8, 0xfa, 0x94, 0x8d, 0x01, 0x0a, 0xf1, 0x51, 0x7f, 0x93, 0x25,
	0xaa, 0xc9, 0x9e, 0xfe, 0x31, 0x7f, 0x0d, 0x4e, 0x0c, 0xf4, 0x1b, 0x40, 0x61, 0x83, 0xde, 0xe3,
	0xd5, 0xab, 0xd4, 0xfb, 0x72, 0xf3, 0x47, 0xa9, 0xc0, 0x05, 0x6c, 0x67, 0x17, 0x19, 0x7d, 0xa1,
	0x13, 0xd1, 0xee, 0xba, 0xce, 0x64, 0xf5, 0xce, 0x8f, 0xfe, 0x33, 0xe0, 0x33, 0x25, 0x8e, 0xf2,
	0x2c, 0xe1, 0x74, 0x05, 0x8d, 0xdc, 0x42, 0xd4, 0x2b, 0xe0, 0xeb, 0x53, 0xd1, 0xeb, 0x6f, 0xfc,
	0x26, 0x8f, 0x76, 0x06, 0x95, 0xc4, 0x2c, 0xa4, 0x89, 0xa0, 0x79, 0xd9, 0xdb, 0x5f, 0x4f, 0x67,
	0xb0, 0xf1, 0x37, 0x7f, 0x5b, 0x5c, 0x9e, 0xe9, 0xbb, 0x7f, 0x70, 0x40, 0xf8, 0x0b, 0xa6, 0xa3,
	0x93, 0xd1, 0xf9, 0xb1, 0xfe, 0xf3, 0x7b, 0xd8, 0x4e, 0x57, 0xa7, 0x1f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xf8, 0xd3, 0x49, 0xc0, 0x13, 0x07, 0x00, 0x00,
}
