// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloMessage struct {
	UdpPort              uint32   `protobuf:"varint,1,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloMessage) Reset()         { *m = HelloMessage{} }
func (m *HelloMessage) String() string { return proto.CompactTextString(m) }
func (*HelloMessage) ProtoMessage()    {}
func (*HelloMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *HelloMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloMessage.Unmarshal(m, b)
}
func (m *HelloMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloMessage.Marshal(b, m, deterministic)
}
func (m *HelloMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloMessage.Merge(m, src)
}
func (m *HelloMessage) XXX_Size() int {
	return xxx_messageInfo_HelloMessage.Size(m)
}
func (m *HelloMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HelloMessage proto.InternalMessageInfo

func (m *HelloMessage) GetUdpPort() uint32 {
	if m != nil {
		return m.UdpPort
	}
	return 0
}

type SetStationMessage struct {
	StationNumber        uint32   `protobuf:"varint,1,opt,name=station_number,json=stationNumber,proto3" json:"station_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStationMessage) Reset()         { *m = SetStationMessage{} }
func (m *SetStationMessage) String() string { return proto.CompactTextString(m) }
func (*SetStationMessage) ProtoMessage()    {}
func (*SetStationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *SetStationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStationMessage.Unmarshal(m, b)
}
func (m *SetStationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStationMessage.Marshal(b, m, deterministic)
}
func (m *SetStationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStationMessage.Merge(m, src)
}
func (m *SetStationMessage) XXX_Size() int {
	return xxx_messageInfo_SetStationMessage.Size(m)
}
func (m *SetStationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SetStationMessage proto.InternalMessageInfo

func (m *SetStationMessage) GetStationNumber() uint32 {
	if m != nil {
		return m.StationNumber
	}
	return 0
}

type WelcomeMessage struct {
	NumStations          uint32   `protobuf:"varint,1,opt,name=num_stations,json=numStations,proto3" json:"num_stations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WelcomeMessage) Reset()         { *m = WelcomeMessage{} }
func (m *WelcomeMessage) String() string { return proto.CompactTextString(m) }
func (*WelcomeMessage) ProtoMessage()    {}
func (*WelcomeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *WelcomeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WelcomeMessage.Unmarshal(m, b)
}
func (m *WelcomeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WelcomeMessage.Marshal(b, m, deterministic)
}
func (m *WelcomeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WelcomeMessage.Merge(m, src)
}
func (m *WelcomeMessage) XXX_Size() int {
	return xxx_messageInfo_WelcomeMessage.Size(m)
}
func (m *WelcomeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WelcomeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WelcomeMessage proto.InternalMessageInfo

func (m *WelcomeMessage) GetNumStations() uint32 {
	if m != nil {
		return m.NumStations
	}
	return 0
}

type AnnounceMessage struct {
	SongName             string   `protobuf:"bytes,1,opt,name=song_name,json=songName,proto3" json:"song_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnounceMessage) Reset()         { *m = AnnounceMessage{} }
func (m *AnnounceMessage) String() string { return proto.CompactTextString(m) }
func (*AnnounceMessage) ProtoMessage()    {}
func (*AnnounceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *AnnounceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnounceMessage.Unmarshal(m, b)
}
func (m *AnnounceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnounceMessage.Marshal(b, m, deterministic)
}
func (m *AnnounceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnounceMessage.Merge(m, src)
}
func (m *AnnounceMessage) XXX_Size() int {
	return xxx_messageInfo_AnnounceMessage.Size(m)
}
func (m *AnnounceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnounceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AnnounceMessage proto.InternalMessageInfo

func (m *AnnounceMessage) GetSongName() string {
	if m != nil {
		return m.SongName
	}
	return ""
}

type InvalidCommandMessage struct {
	ReplyString          string   `protobuf:"bytes,1,opt,name=reply_string,json=replyString,proto3" json:"reply_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidCommandMessage) Reset()         { *m = InvalidCommandMessage{} }
func (m *InvalidCommandMessage) String() string { return proto.CompactTextString(m) }
func (*InvalidCommandMessage) ProtoMessage()    {}
func (*InvalidCommandMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *InvalidCommandMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidCommandMessage.Unmarshal(m, b)
}
func (m *InvalidCommandMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidCommandMessage.Marshal(b, m, deterministic)
}
func (m *InvalidCommandMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidCommandMessage.Merge(m, src)
}
func (m *InvalidCommandMessage) XXX_Size() int {
	return xxx_messageInfo_InvalidCommandMessage.Size(m)
}
func (m *InvalidCommandMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidCommandMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidCommandMessage proto.InternalMessageInfo

func (m *InvalidCommandMessage) GetReplyString() string {
	if m != nil {
		return m.ReplyString
	}
	return ""
}

type DisconnectRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(m, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

type DisconnectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectResponse) Reset()         { *m = DisconnectResponse{} }
func (m *DisconnectResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectResponse) ProtoMessage()    {}
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *DisconnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResponse.Unmarshal(m, b)
}
func (m *DisconnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResponse.Marshal(b, m, deterministic)
}
func (m *DisconnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResponse.Merge(m, src)
}
func (m *DisconnectResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectResponse.Size(m)
}
func (m *DisconnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResponse proto.InternalMessageInfo

func (m *DisconnectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ServerEvent struct {
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Announce
	//	*ServerEvent_Invalid
	Event                isServerEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ServerEvent) Reset()         { *m = ServerEvent{} }
func (m *ServerEvent) String() string { return proto.CompactTextString(m) }
func (*ServerEvent) ProtoMessage()    {}
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{7}
}

func (m *ServerEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerEvent.Unmarshal(m, b)
}
func (m *ServerEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerEvent.Marshal(b, m, deterministic)
}
func (m *ServerEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerEvent.Merge(m, src)
}
func (m *ServerEvent) XXX_Size() int {
	return xxx_messageInfo_ServerEvent.Size(m)
}
func (m *ServerEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ServerEvent proto.InternalMessageInfo

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Announce struct {
	Announce *AnnounceMessage `protobuf:"bytes,1,opt,name=announce,proto3,oneof"`
}

type ServerEvent_Invalid struct {
	Invalid *InvalidCommandMessage `protobuf:"bytes,2,opt,name=invalid,proto3,oneof"`
}

func (*ServerEvent_Announce) isServerEvent_Event() {}

func (*ServerEvent_Invalid) isServerEvent_Event() {}

func (m *ServerEvent) GetEvent() isServerEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ServerEvent) GetAnnounce() *AnnounceMessage {
	if x, ok := m.GetEvent().(*ServerEvent_Announce); ok {
		return x.Announce
	}
	return nil
}

func (m *ServerEvent) GetInvalid() *InvalidCommandMessage {
	if x, ok := m.GetEvent().(*ServerEvent_Invalid); ok {
		return x.Invalid
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerEvent_Announce)(nil),
		(*ServerEvent_Invalid)(nil),
	}
}

func init() {
	proto.RegisterType((*HelloMessage)(nil), "protocol.HelloMessage")
	proto.RegisterType((*SetStationMessage)(nil), "protocol.SetStationMessage")
	proto.RegisterType((*WelcomeMessage)(nil), "protocol.WelcomeMessage")
	proto.RegisterType((*AnnounceMessage)(nil), "protocol.AnnounceMessage")
	proto.RegisterType((*InvalidCommandMessage)(nil), "protocol.InvalidCommandMessage")
	proto.RegisterType((*DisconnectRequest)(nil), "protocol.DisconnectRequest")
	proto.RegisterType((*DisconnectResponse)(nil), "protocol.DisconnectResponse")
	proto.RegisterType((*ServerEvent)(nil), "protocol.ServerEvent")
}

func init() {
	proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0)
}

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xbb, 0x48, 0x90, 0xcd, 0xa4, 0x4d, 0x55, 0xa3, 0xa2, 0x34, 0x45, 0x02, 0x2c, 0x90,
	0xe0, 0x40, 0x5a, 0xa5, 0x07, 0x50, 0x11, 0x07, 0x52, 0x10, 0xe1, 0x40, 0x85, 0x76, 0x0f, 0x48,
	0x5c, 0x56, 0xee, 0xee, 0x28, 0x2c, 0x5d, 0x8f, 0x17, 0x8f, 0x37, 0xa8, 0xef, 0xc0, 0x2b, 0xf2,
	0x2e, 0xa8, 0x1b, 0xef, 0x1f, 0xb5, 0xbd, 0xd9, 0x9f, 0xbf, 0x9f, 0xc7, 0x9f, 0x67, 0x60, 0x5c,
	0x5a, 0xe3, 0x4c, 0x6a, 0x8a, 0x59, 0xbd, 0x10, 0x61, 0xb3, 0x97, 0xaf, 0x60, 0x7b, 0x89, 0x45,
	0x61, 0xbe, 0x22, 0xb3, 0x5a, 0xa1, 0x38, 0x80, 0xb0, 0xca, 0xca, 0xa4, 0x34, 0xd6, 0x4d, 0x82,
	0xa7, 0xc1, 0xcb, 0x9d, 0x68, 0x50, 0x65, 0xe5, 0x37, 0x63, 0x9d, 0x3c, 0x85, 0xbd, 0x18, 0x5d,
	0xec, 0x94, 0xcb, 0x0d, 0x35, 0xfe, 0x17, 0x30, 0xe6, 0x8d, 0x92, 0x50, 0xa5, 0x2f, 0xd0, 0x7a,
	0x6a, 0xc7, 0xab, 0xe7, 0xb5, 0x28, 0x4f, 0x60, 0xfc, 0x1d, 0x8b, 0xd4, 0x68, 0x6c, 0xc0, 0x67,
	0xb0, 0x4d, 0x95, 0x4e, 0xbc, 0x8d, 0x3d, 0x36, 0xa2, 0x4a, 0xfb, 0x0a, 0x2c, 0x67, 0xb0, 0xfb,
	0x81, 0xc8, 0x54, 0x94, 0xb6, 0xd4, 0x21, 0x0c, 0xd9, 0xd0, 0x2a, 0x21, 0xa5, 0xb1, 0x46, 0x86,
	0x51, 0x78, 0x2d, 0x9c, 0x2b, 0x8d, 0xf2, 0x14, 0xf6, 0xbf, 0xd0, 0x5a, 0x15, 0x79, 0x76, 0x66,
	0xb4, 0x56, 0x94, 0xf5, 0x6a, 0x59, 0x2c, 0x8b, 0xab, 0x84, 0x9d, 0xcd, 0x69, 0xe5, 0xc1, 0x51,
	0xad, 0xc5, 0xb5, 0x24, 0x1f, 0xc2, 0xde, 0xc7, 0x9c, 0x53, 0x43, 0x84, 0xa9, 0x8b, 0xf0, 0x77,
	0x85, 0xec, 0xe4, 0x0c, 0x44, 0x5f, 0xe4, 0xd2, 0x10, 0xa3, 0x98, 0xc0, 0x80, 0xab, 0x34, 0x45,
	0xde, 0x3c, 0x3a, 0x8c, 0x9a, 0xad, 0xfc, 0x1b, 0xc0, 0x28, 0x46, 0xbb, 0x46, 0xfb, 0x69, 0x8d,
	0xe4, 0xc4, 0x1b, 0x08, 0x95, 0x0f, 0x50, 0x5b, 0x47, 0xf3, 0x83, 0x59, 0xdb, 0x89, 0x1b, 0xd1,
	0x96, 0x5b, 0x51, 0x6b, 0x16, 0xef, 0x60, 0x90, 0x6f, 0x92, 0x4c, 0xee, 0xd5, 0xdc, 0x93, 0x8e,
	0xbb, 0x33, 0xe2, 0x72, 0x2b, 0x6a, 0x88, 0xc5, 0x00, 0xee, 0xe3, 0x75, 0xf9, 0xf9, 0xbf, 0x00,
	0x76, 0x63, 0x32, 0x7f, 0x52, 0xc5, 0xee, 0xcc, 0x90, 0xb3, 0xa6, 0x10, 0xef, 0x61, 0xb8, 0x54,
	0x94, 0xf1, 0x4f, 0x75, 0x89, 0xe2, 0x51, 0x77, 0x6b, 0x7f, 0x08, 0xa6, 0x93, 0x4e, 0xbf, 0xd1,
	0xb5, 0x05, 0x40, 0x37, 0x03, 0xe2, 0xb0, 0xf3, 0xdd, 0x9a, 0x8c, 0xe9, 0x7e, 0xff, 0xb0, 0xfd,
	0x93, 0xe3, 0x40, 0x7c, 0x06, 0xe8, 0x7e, 0xb5, 0x7f, 0xc7, 0xad, 0x06, 0x4c, 0x1f, 0xdf, 0x7d,
	0xb8, 0x69, 0xc4, 0xe2, 0xf9, 0x0f, 0xc9, 0x3e, 0xde, 0xeb, 0x5f, 0x4a, 0x23, 0x5f, 0x29, 0x9a,
	0x1f, 0xcf, 0xdf, 0x1e, 0x95, 0x97, 0xab, 0xa3, 0x06, 0xbc, 0x78, 0x50, 0xaf, 0x4e, 0xfe, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0x36, 0xc0, 0x64, 0x04, 0x03, 0x00, 0x00,
}
